# Food Trends - UK

the most common food purchased and consumed by the general UK Population.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

In [4]:
#DataFrame

age_path = "../Resources/Exp_AGE_201819.csv"
econ_path = "../Resources/Exp_ECON_201819.csv"
eth_path = "../Resources/Exp_ETH_201819.csv"

df_age = pd.read_csv(age_path)
df_econ = pd.read_csv(econ_path)
df_eth = pd.read_csv(eth_path)

In [3]:
df_age.head()

,Survey_Year,hh_categorisation_number,hh_categorisation_description,Food_code,Food_Code_description,ew:Sum(expenditure_*_household_weight),ew2:Sum(expenditure_squared_*_household_weight_squared),mw:Sum(members_of_household_*_household_weight),mw2:(Sum(members_of_household_squared_*_household_weight_squared),ewmw:Sum(expenditure_*_weighted_number_of_household_members_*_household_weight),Combined_hh_categorisation_and_food_code,Estimate_of_average_expenditure:0.5*(ew/mw),calc1:ew2/(ew*ew),calc2:ewmw/(ew*mw),calc3:mw2/(mw*mw),standard_error:estimate_of_average_expenditure_*_(Square_Root(calc1-calc2+calc3),residual_standard_error:standard_error_*_100/Estimate_of_average_expenditure
0,201819,1,Under 30,402,UHT whole milk,264.10,6.974881e+04,5755.08,274339.0194,1.468396e+03,1_402,0.022945,1.000000,0.001932,0.008283,0.023018,100.317034
1,201819,1,Under 30,404,Pasteurised or homogenised whole milk,193620.64,1.396411e+09,5755.08,274339.0194,8.305295e+06,1_404,16.821716,0.037249,0.014907,0.008283,2.943793,17.499955
2,201819,1,Under 30,901,Condensed or evaporated milk,5211.00,1.009692e+07,5755.08,274339.0194,4.266809e+05,1_901,0.452730,0.371832,0.028455,0.008283,0.268473,59.300927
3,201819,1,Under 30,1102,Infant or baby milks - ready to drink,0.00,0.000000e+00,5755.08,274339.0194,0.000000e+00,1_1102,0.000000,0.000000,0.000000,0.008283,0.000000,0.000000
4,201819,1,Under 30,1103,Infant or baby milks - dried,217879.07,6.203998e+09,5755.08,274339.0194,1.205700e+07,1_1103,18.929282,0.130689,0.019231,0.008283,6.550227,34.603673

In [ ]:
# columns to be cleaned

Survey_Year
hh_categorisation_number
ew2:Sum(expenditure_squared_*_household_weight_squared)
mw:Sum(members_of_household_*_household_weight)
mw2:(Sum(members_of_household_squared_*_household_weight_squared)
ewmw:Sum(expenditure_*_weighted_number_of_household_members_*_household_weight)
     
     
(Sum(members_of_household_squared_*_household_weight_squared)
ewmw:Sum(expenditure_*_weighted_number_of_household_members_*_household_weight)
Combined_hh_categorisation_and_food_code

In [ ]:
#1. What is the most popular food by the Age group 30-39

In [ ]:
#2. What is the most common food purchased by differant ethnic groups

In [ ]:
#3. Food trend by Socio Economic groups (Part time, Full Time, Unemployed, Retired)

In [ ]:
#4. Food Consumption by Age

In [ ]:
#5. Spend on food by Age Group

In [ ]:
# Most Purchase Foods across all groups

In [ ]:
# Least Purchase Foods across all groups

In [ ]:
#Summaries ..... Most pupalr food group across every single socio economic group